/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFPesquisa.java
 *
 * Created on 29/06/2010, 08:32:29
 */
package br.gov.rn.emater.Telas.Pesquisas;

import br.gov.rn.emater.Classes.Caracteristica;
import br.gov.rn.emater.Classes.Doenca;
import br.gov.rn.emater.Classes.Planta;
import br.gov.rn.emater.Classes.Sintoma;
import br.gov.rn.emater.Classes.Tratamento;
import br.gov.rn.emater.Controler.CaracteristicaController;
import br.gov.rn.emater.Controler.DoencaController;
import br.gov.rn.emater.Controler.DoencaSintomaController;
import br.gov.rn.emater.Controler.DoencaTratamentoControler;
import br.gov.rn.emater.Controler.PlantaCaracteristicaController;
import br.gov.rn.emater.Controler.PlantaController;
import br.gov.rn.emater.Controler.SintomaController;
import br.gov.rn.emater.Controler.TratamentoController;
import br.gov.rn.emater.Modelos.DoencasTabela;
import br.gov.rn.emater.Modelos.PlantasTabela;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author cledsonfs
 */
public class JFPesquisa extends javax.swing.JFrame {

    private TratamentoController tratamentoController = new TratamentoController();
    private SintomaController sintomaController = new SintomaController();
    private CaracteristicaController caracteristicaController = new CaracteristicaController();
    private PlantaController plantaController = new PlantaController();
    private DoencaController doencaController = new DoencaController();
    private PlantaCaracteristicaController plantaCaracteristicaController = new PlantaCaracteristicaController();
    private DoencaSintomaController doencaSintomaController = new DoencaSintomaController();
    private DoencaTratamentoControler doencaTratamentoControler = new DoencaTratamentoControler();
    private List<Tratamento> tratamentos = null;
    private List<Sintoma> sintomas = null;
    private List<Caracteristica> caracteristicas = null;
    private List<Planta> plantas = null;

    /** Creates new form JFPesquisa */
    public JFPesquisa() {
        initComponents();
        cargaDados();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCBCaracteristicas = new javax.swing.JComboBox();
        jBCPesquisa = new javax.swing.JButton();
        jBCImprimir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCBPlantas = new javax.swing.JComboBox();
        jBPPesquisa = new javax.swing.JButton();
        jBPImprimir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCBSintomas = new javax.swing.JComboBox();
        jBSPesquisa = new javax.swing.JButton();
        jBSImprimir = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCBTratamento = new javax.swing.JComboBox();
        jBTPesquisar = new javax.swing.JButton();
        jBTImprimir = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:JSIAFF:Pesquisar Informações:.");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 128));
        jLabel1.setText("Pesquisar informações");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(1, 1, 1)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        jPanel6.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setText("Caracteristicas:");

        jCBCaracteristicas.setFont(new java.awt.Font("Arial", 0, 12));

        jBCPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/search_src.gif"))); // NOI18N
        jBCPesquisa.setText("Pesquisar");
        jBCPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCPesquisaActionPerformed(evt);
            }
        });

        jBCImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/print_edit.gif"))); // NOI18N
        jBCImprimir.setText("Imprimir");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 753, Short.MAX_VALUE)
            .add(jPanel6Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jCBCaracteristicas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 495, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBCPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBCImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 72, Short.MAX_VALUE)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCBCaracteristicas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBCPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBCImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Planta por Característica", jPanel6);

        jPanel4.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel6.setText("Planta:");

        jCBPlantas.setFont(new java.awt.Font("Arial", 0, 12));

        jBPPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/search_src.gif"))); // NOI18N
        jBPPesquisa.setText("Pesquisar");
        jBPPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPPesquisaActionPerformed(evt);
            }
        });

        jBPImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/print_edit.gif"))); // NOI18N
        jBPImprimir.setText("Imprimir");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 753, Short.MAX_VALUE)
            .add(0, 753, Short.MAX_VALUE)
            .add(jPanel4Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jCBPlantas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 495, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBPPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBPImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 72, Short.MAX_VALUE)
            .add(0, 72, Short.MAX_VALUE)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCBPlantas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBPPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBPImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doença por Planta", jPanel4);

        jPanel7.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setText("Sintomas:");

        jCBSintomas.setFont(new java.awt.Font("Arial", 0, 12));

        jBSPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/search_src.gif"))); // NOI18N
        jBSPesquisa.setText("Pesquisar");
        jBSPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSPesquisaActionPerformed(evt);
            }
        });

        jBSImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/print_edit.gif"))); // NOI18N
        jBSImprimir.setText("Imprimir");

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jCBSintomas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 495, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBSPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBSImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCBSintomas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBSPesquisa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBSImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doença por Sintoma", jPanel7);

        jPanel8.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setText("Tratamentos:");

        jCBTratamento.setFont(new java.awt.Font("Arial", 0, 12));

        jBTPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/search_src.gif"))); // NOI18N
        jBTPesquisar.setText("Pesquisar");
        jBTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTPesquisarActionPerformed(evt);
            }
        });

        jBTImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/print_edit.gif"))); // NOI18N
        jBTImprimir.setText("Imprimir");

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jPanel8Layout.createSequentialGroup()
                        .add(jCBTratamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 495, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBTPesquisar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBTImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCBTratamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBTPesquisar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBTImprimir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doença por Tratamento", jPanel8);

        jBFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/close_view.gif"))); // NOI18N
        jBFechar.setText("Fechar");
        jBFechar.setToolTipText("Fecha a tela");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial", 0, 10));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .add(jBFechar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(13, 13, 13))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jBFechar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-622)/2, 800, 622);
    }// </editor-fold>//GEN-END:initComponents

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBPPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPPesquisaActionPerformed
        Planta pSel = null;
        for (Planta p : plantas) {
            if (p.getNomepopular().trim().equals(jCBPlantas.getSelectedItem().toString().trim())) {
                pSel = p;
            }
        }
        if (pSel != null) {
            ArrayList<Doenca> doencaResult = (ArrayList<Doenca>) doencaController.getDoencasPorIdPlanta(pSel.getIdplanta());
            jTable1.setModel(new DoencasTabela(doencaResult, false));
            TableRowSorter ts = new TableRowSorter(jTable1.getModel());
            jTable1.setRowSorter(ts);
            jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de registros: " + jTable1.getModel().getRowCount()));
            jTable1.getColumnModel().getColumn(0).setMaxWidth(55);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(65);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(80);
        }
    }//GEN-LAST:event_jBPPesquisaActionPerformed

    private void jBCPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCPesquisaActionPerformed
        Caracteristica cSel = null;
        for (Caracteristica c : caracteristicas) {
            if (c.getDescricao().trim().equals(jCBCaracteristicas.getSelectedItem().toString().trim())) {
                cSel = c;
            }
        }
        if (cSel != null) {
            try {
                ArrayList<Planta> plantaResult = (ArrayList<Planta>) plantaCaracteristicaController.getPlantaPorIdCaracteristica(cSel.getIdcaracteristica());
                jTable1.setModel(new PlantasTabela(plantaResult, false));
                TableRowSorter ts = new TableRowSorter(jTable1.getModel());
                jTable1.setRowSorter(ts);
                jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de registros: " + jTable1.getModel().getRowCount()));
                jTable1.getColumnModel().getColumn(0).setMaxWidth(55);
                jTable1.getColumnModel().getColumn(2).setMaxWidth(65);
                jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
            } catch (Exception ex) {
                Logger.getLogger(JFPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBCPesquisaActionPerformed

    private void jBSPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSPesquisaActionPerformed
        Sintoma sSel = null;
        for (Sintoma s : sintomas) {
            if (s.getDescricao().trim().equals(jCBSintomas.getSelectedItem().toString().trim())) {
                sSel = s;
            }
        }
        if (sSel != null) {
            try {
                ArrayList<Doenca> doencaResult = (ArrayList<Doenca>) doencaSintomaController.getDoencaIdSintoma(sSel.getIdsintoma());
                jTable1.setModel(new DoencasTabela(doencaResult, false));
                TableRowSorter ts = new TableRowSorter(jTable1.getModel());
                jTable1.setRowSorter(ts);
                jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de registros: " + jTable1.getModel().getRowCount()));
                jTable1.getColumnModel().getColumn(0).setMaxWidth(55);
                jTable1.getColumnModel().getColumn(4).setMaxWidth(65);
                jTable1.getColumnModel().getColumn(5).setMaxWidth(80);
            } catch (Exception ex) {
                Logger.getLogger(JFPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBSPesquisaActionPerformed

    private void jBTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTPesquisarActionPerformed
        Tratamento tSel = null;
        for (Tratamento t : tratamentos) {
            if (t.getDescricao().trim().equals(jCBTratamento.getSelectedItem().toString().trim())) {
                tSel = t;
            }
        }
        if (tSel != null) {
            try {
                ArrayList<Doenca> doencaResult = (ArrayList<Doenca>) doencaTratamentoControler.getDoencaIdTratamento(tSel.getIdtratamento());
                jTable1.setModel(new DoencasTabela(doencaResult, false));
                TableRowSorter ts = new TableRowSorter(jTable1.getModel());
                jTable1.setRowSorter(ts);
                jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de registros: " + jTable1.getModel().getRowCount()));
                jTable1.getColumnModel().getColumn(0).setMaxWidth(55);
                jTable1.getColumnModel().getColumn(4).setMaxWidth(65);
                jTable1.getColumnModel().getColumn(5).setMaxWidth(80);
            } catch (Exception ex) {
                Logger.getLogger(JFPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBTPesquisarActionPerformed

    private void cargaDados() {
        try {
            tratamentos = tratamentoController.getTodos();
            sintomas = sintomaController.getTodos();
            caracteristicas = caracteristicaController.getTodos();
            plantas = plantaController.getTodos();
        } catch (Exception ex) {
            Logger.getLogger(JFPesquisa.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultComboBoxModel dcbmTratamento = new DefaultComboBoxModel();
        DefaultComboBoxModel dcbmSintoma = new DefaultComboBoxModel();
        DefaultComboBoxModel dcbmCaracteristica = new DefaultComboBoxModel();
        DefaultComboBoxModel dcbmPlanta = new DefaultComboBoxModel();

        for (Tratamento tratamento : tratamentos) {
            dcbmTratamento.addElement(tratamento.getDescricao().trim());
        }

        for (Sintoma sintoma : sintomas) {
            dcbmSintoma.addElement(sintoma.getDescricao().trim());
        }

        for (Caracteristica caracteristica : caracteristicas) {
            dcbmCaracteristica.addElement(caracteristica.getDescricao().trim());
        }

        for (Planta planta : plantas) {
            dcbmPlanta.addElement(planta.getNomepopular().trim());
        }

        jCBTratamento.setModel(dcbmTratamento);
        jCBSintomas.setModel(dcbmSintoma);
        jCBCaracteristicas.setModel(dcbmCaracteristica);
        jCBPlantas.setModel(dcbmPlanta);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCImprimir;
    private javax.swing.JButton jBCPesquisa;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBPImprimir;
    private javax.swing.JButton jBPPesquisa;
    private javax.swing.JButton jBSImprimir;
    private javax.swing.JButton jBSPesquisa;
    private javax.swing.JButton jBTImprimir;
    private javax.swing.JButton jBTPesquisar;
    private javax.swing.JComboBox jCBCaracteristicas;
    private javax.swing.JComboBox jCBPlantas;
    private javax.swing.JComboBox jCBSintomas;
    private javax.swing.JComboBox jCBTratamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
