/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFCadFamilia.java
 *
 * Created on 31/05/2010, 09:53:18
 */
package br.gov.rn.emater.Telas.Cadastros;

import br.gov.rn.emater.Base.Imprimir;
import br.gov.rn.emater.Classes.Parte;
import br.gov.rn.emater.Classes.Usuario;
import br.gov.rn.emater.Controler.ParteController;
import br.gov.rn.emater.DataSources.ListaPartesDS;
import br.gov.rn.emater.Modelos.ParteTabela;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author cledsonfs
 */
public class JFCadParte extends javax.swing.JFrame {

    private Usuario usuario;
    private boolean alterar = false;
    private ParteController controller = new ParteController();
    private Parte alterarFamilia = null;
    private String menssagem = "";
    private HashMap<String, String> parametros;

    /** Creates new form JFCadFamilia */
    public JFCadParte(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        cargatabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTParte = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBCancAlter = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:JSIAFF:Cadastro de Partes da Planta:.");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 128));
        jLabel1.setText("Cadastro de Partes da Planta");

        jLabel2.setText("Nome:");

        jTFDescricao.setEnabled(false);

        jTParte.setFont(new java.awt.Font("Arial", 0, 10));
        jTParte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTParteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTParte);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/add_obj.gif"))); // NOI18N
        jButton1.setToolTipText("Novo");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/delete_obj.gif"))); // NOI18N
        jButton2.setToolTipText("Excluir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/change_obj.gif"))); // NOI18N
        jButton3.setToolTipText("Alterar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jBCancAlter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/refresh_nav.gif"))); // NOI18N
        jBCancAlter.setToolTipText("Cancelar Alteração");
        jBCancAlter.setFocusable(false);
        jBCancAlter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancAlter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBCancAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancAlterActionPerformed(evt);
            }
        });
        jToolBar1.add(jBCancAlter);

        jBImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/print_edit.gif"))); // NOI18N
        jBImprimir.setFocusable(false);
        jBImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(jBImprimir);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/save_edit.gif"))); // NOI18N
        jButton4.setToolTipText("Salvar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/close_view.gif"))); // NOI18N
        jButton5.setToolTipText("Fechar");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2)
                .addContainerGap())
            .add(jTFDescricao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTFDescricao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .add(jLabel1))
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .add(68, 68, 68)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTFDescricao.setText("");
        jTFDescricao.setEnabled(true);
        jTFDescricao.requestFocus();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTParte.getSelectedRow() > -1) {
            int id = (Integer) jTParte.getValueAt(jTParte.getSelectedRow(), 0);
            Parte parte = controller.localizarPorID(id);
            if (parte != null && parte.getIdparte() > -1) {
                int opc = JOptionPane.showConfirmDialog(this, "Confirma a exclusão do registro?", ".:JSIAFF:Pergunta:.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (opc == 0) {
                    controller.set(parte);
                    try {
                        boolean retorno = controller.excluir();
                        menssagem = controller.getMenssagemRetorno();
                        if (retorno) {
                            JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Mensagem:.", JOptionPane.INFORMATION_MESSAGE);
                            limpaTela();
                            cargatabela();
                        } else {
                            JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Error:.", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(JFCadParte.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        alterar = true;
        jTFDescricao.setEnabled(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Parte parte;
        if (alterar && alterarFamilia != null) {
            parte = alterarFamilia;
        } else {
            parte = new Parte();
        }
        parte.setDescricao(jTFDescricao.getText().trim().toUpperCase());
        parte.setDatacadastro(new Timestamp(new Date().getTime()));
        parte.setIdUsuario(usuario.getIdUsuario());
        controller.set(parte);
        try {
            boolean retorno = controller.salvar(alterar);
            menssagem = controller.getMenssagemRetorno();
            if (retorno) {
                JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Mensagem:.", JOptionPane.INFORMATION_MESSAGE);
                limpaTela();
                cargatabela();
            } else {
                JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Error:.", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(JFCadGenero.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void limpaTela() {
        jTFDescricao.setText("");
        alterar = false;
        alterarFamilia = null;
        jTFDescricao.setEnabled(false);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    private void jTParteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTParteMouseClicked
        if (jTParte.getSelectedRow() > -1) {
            int id = (Integer) jTParte.getValueAt(jTParte.getSelectedRow(), 0);
            alterarFamilia = controller.localizarPorID(id);
            jTFDescricao.setText(alterarFamilia.getDescricao().trim());
        }
}//GEN-LAST:event_jTParteMouseClicked

    private void jBCancAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancAlterActionPerformed
        alterar = false;
        jTFDescricao.setEnabled(false);
}//GEN-LAST:event_jBCancAlterActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        try {
            List<Parte> partes = controller.getTodos();
            parametros = new HashMap<String, String>();
            parametros.put("por", usuario.getLogin());
            new Imprimir(partes, "ModelosRelatorios/listaPartes.jasper", new ListaPartesDS((ArrayList) partes), parametros);
        } catch (Exception ex) {
            Logger.getLogger(JFCadParte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBImprimirActionPerformed

    private void cargatabela() {
        jTParte.setModel(new ParteTabela());
        TableRowSorter ts = new TableRowSorter(jTParte.getModel());
        jTParte.setRowSorter(ts);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de registros: " + jTParte.getModel().getRowCount()));
        jTParte.getColumnModel().getColumn(0).setMaxWidth(55);
        jTParte.getColumnModel().getColumn(2).setMaxWidth(65);
        jTParte.getColumnModel().getColumn(3).setMaxWidth(80);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancAlter;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTable jTParte;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
