/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFCadSintoma.java
 *
 * Created on 01/06/2010, 20:08:01
 */
package br.gov.rn.emater.Telas.Cadastros;

import br.gov.rn.emater.Base.Imprimir;
import br.gov.rn.emater.Classes.Sintoma;
import br.gov.rn.emater.Classes.Usuario;
import br.gov.rn.emater.Controler.SintomaController;
import br.gov.rn.emater.DataSources.ListaSintomasDS;
import br.gov.rn.emater.Modelos.SintomaTabela;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author cledsonfs
 */
public class JFCadSintoma extends javax.swing.JFrame {

    private Usuario usuario;
    private boolean alterar = false;
    private SintomaController controller = new SintomaController();
    private Sintoma alterarSintoma = null;
    private String menssagem = "";
    private HashMap<String, String> parametros;

    /** Creates new form JFCadSintoma */
    public JFCadSintoma(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        cargatabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBCancAlter = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:JSIAFF:Cadastro de Sintomas das Doenças:.");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 128));
        jLabel1.setText("Cadastro dos Sintomas das Doenças");

        jLabel2.setText("Descrição:");

        jTFDescricao.setEnabled(false);

        jTable1.setFont(new java.awt.Font("Arial", 0, 10));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/add_obj.gif"))); // NOI18N
        jButton1.setToolTipText("Novo");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/delete_obj.gif"))); // NOI18N
        jButton2.setToolTipText("Excluir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/change_obj.gif"))); // NOI18N
        jButton3.setToolTipText("Alterar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jBCancAlter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/refresh_nav.gif"))); // NOI18N
        jBCancAlter.setToolTipText("Cancelar Alteração");
        jBCancAlter.setFocusable(false);
        jBCancAlter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancAlter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBCancAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancAlterActionPerformed(evt);
            }
        });
        jToolBar1.add(jBCancAlter);

        jBImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/print_edit.gif"))); // NOI18N
        jBImprimir.setFocusable(false);
        jBImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(jBImprimir);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/save_edit.gif"))); // NOI18N
        jButton4.setToolTipText("Salvar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/rn/emater/icones/close_view.gif"))); // NOI18N
        jButton5.setToolTipText("Fechar");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2)
                .addContainerGap())
            .add(jTFDescricao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTFDescricao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .add(jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRow() > -1) {
            int id = (Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            alterarSintoma = controller.localizarPorID(id);
            jTFDescricao.setText(alterarSintoma.getDescricao().trim());
        }
}//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTFDescricao.setText("");
        jTFDescricao.setEnabled(true);
        jTFDescricao.requestFocus();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            int id = (Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            Sintoma sintoma = controller.localizarPorID(id);
            if (sintoma != null && sintoma.getIdsintoma() > -1) {
                int opc = JOptionPane.showConfirmDialog(this, "Confirma a exclusão do registro?", ".:JSIAFF:Pergunta:.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (opc == 0) {
                    controller.set(sintoma);
                    try {
                        boolean retorno = controller.excluir();
                        menssagem = controller.getMenssagemRetorno();
                        if (retorno) {
                            JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Mensagem:.", JOptionPane.INFORMATION_MESSAGE);
                            limpaTela();
                            cargatabela();
                        } else {
                            JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Error:.", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(JFCadSintoma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    cargatabela();
                }
            }
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        alterar = true;
        jTFDescricao.setEnabled(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Sintoma sintoma;
        if (alterar && alterarSintoma != null) {
            sintoma = alterarSintoma;
        } else {
            sintoma = new Sintoma();
        }
        sintoma.setDescricao(jTFDescricao.getText().trim().toUpperCase());
        sintoma.setDatacadastro(new Timestamp(new Date().getTime()));
        sintoma.setIdUsuario(usuario.getIdUsuario());
        controller.set(sintoma);
        try {
            boolean retorno = controller.salvar(alterar);
            menssagem = controller.getMenssagemRetorno();
            if (retorno) {
                JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Mensagem:.", JOptionPane.INFORMATION_MESSAGE);
                limpaTela();
                cargatabela();
            } else {
                JOptionPane.showMessageDialog(this, menssagem, ".:JSIAFF:Error:.", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(JFCadSintoma.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_jButton4ActionPerformed

    private void limpaTela() {
        jTFDescricao.setText("");
        alterar = false;
        alterarSintoma = null;
        jTFDescricao.setEnabled(false);
        menssagem = "";
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    private void jBCancAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancAlterActionPerformed
        alterar = false;
        jTFDescricao.setEnabled(false);
}//GEN-LAST:event_jBCancAlterActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        try {
            List<Sintoma> sintomas = controller.getTodos();
            parametros = new HashMap<String, String>();
            parametros.put("por", usuario.getLogin());
            new Imprimir(sintomas, "ModelosRelatorios/listaSintomas.jasper", new ListaSintomasDS((ArrayList) sintomas), parametros);
        } catch (Exception ex) {
            Logger.getLogger(JFCadSintoma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBImprimirActionPerformed
    private void cargatabela() {
        jTable1.setModel(new SintomaTabela());
        TableRowSorter ts = new TableRowSorter(jTable1.getModel());
        jTable1.setRowSorter(ts);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de registros: " + jTable1.getModel().getRowCount()));
        jTable1.getColumnModel().getColumn(0).setMaxWidth(55);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(65);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancAlter;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
